### ISSUE TITLE
I got an error.

### ISSUE THREAD

**Issue by HeinKoZin** [mahmoud-eskandari/vuemastery-dl#22]
### I got an error like this:
Error On video:258707456
TypeError: "listener" argument must be a function
    at ClientRequest.once (events.js:340:11)
    at new ClientRequest (_http_client.js:164:10)
    at Object.request (http.js:38:10)
    at Object.request (https.js:239:15)
    at Object.get (https.js:243:21)
    at /content/vuemastery-dl/mirror.js:76:15
    at new Promise (<anonymous>)
    at getVimeoPageByID (/content/vuemastery-dl/mirror.js:69:12)
    at startDownloadByID (/content/vuemastery-dl/mirror.js:27:30)
    at /content/vuemastery-dl/mirror.js:13:13

**Comment by mahmoud-eskandari** [comment]
please insert your command and target course
