### ISSUE TITLE
Scaling-vue-with-nuxt-js has download issue

### ISSUE THREAD

**Issue by Mobasher-NetLinks** [mahmoud-eskandari/vuemastery-dl#24]
When download the **_Scaling-vue-with-nuxt-js_**  following issue occur.

   ```
 events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '07 - Async/Await from Vue Mastery.mp4'
Emitted 'error' event on WriteStream instance at:
    at internal/fs/streams.js:320:12
    at FSReqCallback.oncomplete (fs.js:154:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '07 - Async/Await from Vue Mastery.mp4'
}
````

**Comment by Mobasher-NetLinks** [comment]
Still it has error `replaceAll is not a function`, why not only used a regex for replacing `courseTitle.replace(/\//g, '-')`

**Comment by mahmoud-eskandari** [comment]
It fixed!
